const alienPlanets = [
    {
      id: 1,
      name: "Zorbon",
      emoji: "🪐",
      distanceFromEarth: "320 light years",
      hasLife: true,
      atmosphere: "nitrogen-oxygen",
      text: "Zorbon is 320 light years miles from earth. Zorbon is believed to have life. The atmosphere of Zorbon is nitrogen-oxygen. " ,
    },
    {
      id: 2,
      name: "Xenophylia",
      emoji: "🌌",
      distanceFromEarth: "450 light years",
      hasLife: false,
      atmosphere: "methane-argon",
      text: "Xenophylia is 450 light years miles from earth. Xenophylia is believed to not have life. The atmosphere of Xenophylia is methane-argon.",
    },
    {
      id: 3,
      name: "Quasar Quinta",
      emoji: "💫",
      distanceFromEarth: "1290 light years",
      hasLife: true,
      atmosphere: "ammonia-rich",
      text: "Quasar Quinta is 1290 light years miles from earth. Quasar Quinta is believed to have life. The atmosphere of Quasar Quinta is ammonia-rich.",
    },
    {
      id: 4,
      name: "Galaxara",
      emoji: "✨",
      distanceFromEarth: "85 light years",
      hasLife: false,
      atmosphere: "carbon dioxide",
      text: "Galaxara is 85 light years miles from earth. Galaxara is believed to not have life. The atmosphere of Galaxara is carbon dioxide.",
    },
    {
      id: 5,
      name: "Lunaris",
      emoji: "🌑",
      distanceFromEarth: "600 light years",
      hasLife: true,
      atmosphere: "oxygen-argon",
      text: "Lunaris is 600 light years miles from earth. Lunaris is believed to have life. The atmosphere of Lunaris is oxygen-argon.",
    },
    {
      id: 6,
      name: "Cosmica",
      emoji: "🌠",
      distanceFromEarth: "2500 light years",
      hasLife: false,
      atmosphere: "hydrogen-helium",
      text: "Cosmica is 2500 light years miles from earth. Cosmica is believed to not have life. The atmosphere of Cosmica is hydrogen-helium.",
    },
    {
      id: 7,
      name: "Nebulon",
      emoji: "🌫️",
      distanceFromEarth: "1100 light years",
      hasLife: true,
      atmosphere: "sulfuric acid",
      text: "Nebulon is 1100 light years miles from earth. Nebulon is believed to have life. The atmosphere of Nebulon is sulfuric acid.",
    },
    {
      id: 8,
      name: "Andromia",
      emoji: "🛸",
      distanceFromEarth: "75 light years",
      hasLife: false,
      atmosphere: "chlorine",
      text: "Andromia is 75 light years miles from earth. Andromia is believed to not have life. The atmosphere of Andromia is chlorine.",
    },
    {
      id: 9,
      name: "Stellaris",
      emoji: "🌟",
      distanceFromEarth: "300 light years",
      hasLife: true,
      atmosphere: "nitrogen-methane",
      text: "Stellaris is 300 light years miles from earth. Stellaris is believed to have life. The atmosphere of Stellaris is nitrogen-methane.",
    },
    {
      id: 10,
      name: "Vortexa",
      emoji: "🌀",
      distanceFromEarth: "2200 light years",
      hasLife: false,
      atmosphere: "neon-xenon",
      text: "Vortexa is 2200 light years miles from earth. Vortexa is believed to not have life. The atmosphere of Vortexa is neon-xenon.",
    },
  ];
  

  export default alienPlanets;